name: Ubuntu - Deploy docs
on: 
  push:
    branches: 
      - main
      - master

jobs:
  ubuntu-deploy-docs:
    name: Ubuntu - Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install Crystal libs
        run: shards install
      - name: raylib-cr post-install
        run: sh ./lib/raylib-cr/rsrc/install-lib.sh
      - name: Build site
        run: crystal docs
      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}